In [4]:
import pandas as pd
import numpy as np
import os
import shutil

In [5]:
# PyTorch
# addition for reading videos
import torchvision.transforms.functional as F
from torchvision.io import read_video

In [6]:
df_study1=pd.read_csv("annotation datasets/test_S_rEF_vs_nrEF.csv", header=None) #,  index_col= 1, header=None),

In [7]:
df_study2=pd.read_csv("annotation datasets/train_S_rEF_vs_nrEF.csv", header=None) #,  index_col= 1, header=None),

In [8]:
df_study = pd.concat([df_study1, df_study2])

In [9]:
df_study

                                                      0            1  2    3
0     gs://cloud-ai-platform-d44a8260-adf9-4b26-91d3...  not_reduced  0  inf
1     gs://cloud-ai-platform-d44a8260-adf9-4b26-91d3...  not_reduced  0  inf
2     gs://cloud-ai-platform-d44a8260-adf9-4b26-91d3...  not_reduced  0  inf
3     gs://cloud-ai-platform-d44a8260-adf9-4b26-91d3...  not_reduced  0  inf
4     gs://cloud-ai-platform-d44a8260-adf9-4b26-91d3...  not_reduced  0  inf
...                                                 ...          ... ..  ...
1238  gs://cloud-ai-platform-d44a8260-adf9-4b26-91d3...      reduced  0  inf
1239  gs://cloud-ai-platform-d44a8260-adf9-4b26-91d3...      reduced  0  inf
1240  gs://cloud-ai-platform-d44a8260-adf9-4b26-91d3...      reduced  0  inf
1241  gs://cloud-ai-platform-d44a8260-adf9-4b26-91d3...      reduced  0  inf
1242  gs://cloud-ai-platform-d44a8260-adf9-4b26-91d3...      reduced  0  inf

[1658 rows x 4 columns]

In [10]:
df_study.drop(df_study.columns[[2,3]], axis=1, inplace=True)

In [11]:
df_study

                                                      0            1
0     gs://cloud-ai-platform-d44a8260-adf9-4b26-91d3...  not_reduced
1     gs://cloud-ai-platform-d44a8260-adf9-4b26-91d3...  not_reduced
2     gs://cloud-ai-platform-d44a8260-adf9-4b26-91d3...  not_reduced
3     gs://cloud-ai-platform-d44a8260-adf9-4b26-91d3...  not_reduced
4     gs://cloud-ai-platform-d44a8260-adf9-4b26-91d3...  not_reduced
...                                                 ...          ...
1238  gs://cloud-ai-platform-d44a8260-adf9-4b26-91d3...      reduced
1239  gs://cloud-ai-platform-d44a8260-adf9-4b26-91d3...      reduced
1240  gs://cloud-ai-platform-d44a8260-adf9-4b26-91d3...      reduced
1241  gs://cloud-ai-platform-d44a8260-adf9-4b26-91d3...      reduced
1242  gs://cloud-ai-platform-d44a8260-adf9-4b26-91d3...      reduced

[1658 rows x 2 columns]

df_study=df_study.reset_index()

In [13]:
df_study.rename(columns = {0:'Videopath', 1:'EFClass' }, inplace = True)

In [14]:
df_study

                                              Videopath      EFClass
0     gs://cloud-ai-platform-d44a8260-adf9-4b26-91d3...  not_reduced
1     gs://cloud-ai-platform-d44a8260-adf9-4b26-91d3...  not_reduced
2     gs://cloud-ai-platform-d44a8260-adf9-4b26-91d3...  not_reduced
3     gs://cloud-ai-platform-d44a8260-adf9-4b26-91d3...  not_reduced
4     gs://cloud-ai-platform-d44a8260-adf9-4b26-91d3...  not_reduced
...                                                 ...          ...
1238  gs://cloud-ai-platform-d44a8260-adf9-4b26-91d3...      reduced
1239  gs://cloud-ai-platform-d44a8260-adf9-4b26-91d3...      reduced
1240  gs://cloud-ai-platform-d44a8260-adf9-4b26-91d3...      reduced
1241  gs://cloud-ai-platform-d44a8260-adf9-4b26-91d3...      reduced
1242  gs://cloud-ai-platform-d44a8260-adf9-4b26-91d3...      reduced

[1658 rows x 2 columns]

In [15]:
video_list = []
for idx, row in df_study.iterrows():
    name = row.Videopath.split('curated/')[1][:-4]
    video_list.append(name)
df_study['FileName']=video_list

In [16]:
df_study

,Videopath,EFClass,FileName
0,gs://cloud-ai-platform-d44a8260-adf9-4b26-91d3...,not_reduced,0X23AA500225C0E94E
1,gs://cloud-ai-platform-d44a8260-adf9-4b26-91d3...,not_reduced,0X2C12A8B71D39E8DA
2,gs://cloud-ai-platform-d44a8260-adf9-4b26-91d3...,not_reduced,0X22FAC36B13D3526C
3,gs://cloud-ai-platform-d44a8260-adf9-4b26-91d3...,not_reduced,0X57A074E488CFB7AC
4,gs://cloud-ai-platform-d44a8260-adf9-4b26-91d3...,not_reduced,0XD3B557874B91D0D
...,...,...,...
1238,gs://cloud-ai-platform-d44a8260-adf9-4b26-91d3...,reduced,0XBFB290E3C10D76A
1239,gs://cloud-ai-platform-d44a8260-adf9-4b26-91d3...,reduced,0XD4659C3A1FA9518
1240,gs://cloud-ai-platform-d44a8260-adf9-4b26-91d3...,reduced,0XDA3CBEA102E1D11
1241,gs://cloud-ai-platform-d44a8260-adf9-4b26-91d3...,reduced,0XEFDBFDCA164AB94
1242,gs://cloud-ai-platform-d44a8260-adf9-4b26-91d3...,reduced,0XFEBEEFF93F6FEB9

In [18]:
df_study

,Videopath,EFClass,FileName
0,gs://cloud-ai-platform-d44a8260-adf9-4b26-91d3...,not_reduced,0X23AA500225C0E94E
1,gs://cloud-ai-platform-d44a8260-adf9-4b26-91d3...,not_reduced,0X2C12A8B71D39E8DA
2,gs://cloud-ai-platform-d44a8260-adf9-4b26-91d3...,not_reduced,0X22FAC36B13D3526C
3,gs://cloud-ai-platform-d44a8260-adf9-4b26-91d3...,not_reduced,0X57A074E488CFB7AC
4,gs://cloud-ai-platform-d44a8260-adf9-4b26-91d3...,not_reduced,0XD3B557874B91D0D
...,...,...,...
1238,gs://cloud-ai-platform-d44a8260-adf9-4b26-91d3...,reduced,0XBFB290E3C10D76A
1239,gs://cloud-ai-platform-d44a8260-adf9-4b26-91d3...,reduced,0XD4659C3A1FA9518
1240,gs://cloud-ai-platform-d44a8260-adf9-4b26-91d3...,reduced,0XDA3CBEA102E1D11
1241,gs://cloud-ai-platform-d44a8260-adf9-4b26-91d3...,reduced,0XEFDBFDCA164AB94
1242,gs://cloud-ai-platform-d44a8260-adf9-4b26-91d3...,reduced,0XFEBEEFF93F6FEB9

In [19]:
df_study = df_study.drop("Videopath", axis=1)

In [22]:
df_study

          EFClass            FileName
0     not_reduced  0X23AA500225C0E94E
1     not_reduced  0X2C12A8B71D39E8DA
2     not_reduced  0X22FAC36B13D3526C
3     not_reduced  0X57A074E488CFB7AC
4     not_reduced   0XD3B557874B91D0D
...           ...                 ...
1238      reduced   0XBFB290E3C10D76A
1239      reduced   0XD4659C3A1FA9518
1240      reduced   0XDA3CBEA102E1D11
1241      reduced   0XEFDBFDCA164AB94
1242      reduced   0XFEBEEFF93F6FEB9

[1658 rows x 2 columns]

In [23]:
df = pd.read_csv("EchoNet-Dynamic/FileList.csv", index_col= 0)

In [24]:
len(df)

10030

In [27]:
result = pd.merge(df_study, df, how="inner", on=["FileName"])

In [28]:
result

,EFClass,FileName,EF,ESV,EDV,FrameHeight,FrameWidth,FPS,NumberOfFrames,Split
0,not_reduced,0X23AA500225C0E94E,48.796961,29.035126,56.705864,112,112,50,134,VAL
1,not_reduced,0X2C12A8B71D39E8DA,43.300493,38.610863,68.097352,112,112,50,137,TEST
2,not_reduced,0X22FAC36B13D3526C,43.466400,66.474564,117.584169,112,112,50,155,TEST
3,not_reduced,0X57A074E488CFB7AC,47.237729,44.712118,84.742595,112,112,50,186,VAL
4,not_reduced,0XD3B557874B91D0D,48.845837,45.734412,89.405064,112,112,50,184,TEST
...,...,...,...,...,...,...,...,...,...,...
1653,reduced,0XBFB290E3C10D76A,21.772368,200.597983,256.428551,112,112,50,150,TRAIN
1654,reduced,0XD4659C3A1FA9518,34.774695,44.838323,68.743754,112,112,50,164,TRAIN
1655,reduced,0XDA3CBEA102E1D11,25.564947,80.453612,108.085652,112,112,50,165,TRAIN
1656,reduced,0XEFDBFDCA164AB94,30.248452,89.791515,128.730498,112,112,50,199,TRAIN
1657,reduced,0XFEBEEFF93F6FEB9,30.429669,60.366313,86.770197,112,112,50,109,TRAIN

In [29]:
result.query(' EFClass == "reduced"  and Split == "TRAIN" ').sample(n= 2, random_state = 42)

,EFClass,FileName,EF,ESV,EDV,FrameHeight,FrameWidth,FPS,NumberOfFrames,Split
1086,reduced,0X60D399F5596817FD,30.744037,66.831442,96.499188,112,112,50,200,TRAIN
1621,reduced,0X60C1562BC81D2CFD,19.780814,64.046414,79.839272,112,112,50,133,TRAIN

In [30]:
result.query(' EFClass == "not_reduced"  and Split == "TRAIN" ').sample(n= 2, random_state = 42)

,EFClass,FileName,EF,ESV,EDV,FrameHeight,FrameWidth,FPS,NumberOfFrames,Split
664,not_reduced,0XD931DD5F6E68BB,61.700065,34.165733,89.205720,112,112,50,181,TRAIN
814,not_reduced,0X2EC3E1044DE5412D,55.972242,28.623940,65.013395,112,112,50,170,TRAIN

## converting to 50 frames with ffmpeg and place in movienet_50f

In [32]:
import av
import ffmpeg

In [34]:
def get_info(video):
    probe = ffmpeg.probe(video)
    video_info = next(s for s in probe['streams'] if s['codec_type'] == 'video')
    width = int(video_info['width'])
    height = int(video_info['height'])
    num_frames = int(video_info['nb_frames'])
    duration = float(video_info['duration'])
    return num_frames, duration, width, height

In [36]:
# transfer all study videos
origin =  "EchoNet-Dynamic/Videos/"
target = "movienet_50f/"
clip_length = 50
i = 0
for index, row in result.iterrows(): #query(' EFClass != "midrange" and Split in ["TRAIN"] ').iterrows():
    i = i+1
    if i%50 == 0:
        print(i, "files copied")
       
    #print( index,row["EFClass"],row["Split"].lower() )
    file_name = row["FileName"]+".avi"
    if os.path.exists(origin + file_name):
        t_final = target+row["Split"].lower()+"/"+row["EFClass"]+"/"+row["FileName"]+".mp4"
        #print(t_final)
        
        if not os.path.exists(t_final):            
            # transform to clip_length frames mp4
            ffmpeg.input(origin+file_name).output("output.mp4").overwrite_output().run()        
            num_frames, duration, _, _ = get_info("output.mp4")
            #fps_in = num_frames / duration
            fps_out = clip_length / duration # 4 * clip_length / duration
            start_time = 0
            #end_time = duration / 4
            #end_frame = int(np.ceil(num_frames/4))
    
            (
                ffmpeg
                    .input("output.mp4")
                    #.trim(start=0, duration = duration / 4)
                    .filter('fps', fps=fps_out, round='up')
                    .output('output_hoped.mp4')
                    .overwrite_output()
                    .run()
            )
            
            num_frames_out, duration_out, _ , _ = get_info("output_hoped.mp4")
            if num_frames_out < clip_length:
                print(num_frames_out, "frames for "+ t_final)
            #input_file = ffmpeg.input("output16hoped.mp4")
            #output_file = ffmpeg.output(input_file.trim(start_frame=0, end_frame= 16), t_final')
            #ffmpeg.overwrite_output().run(output_file)
            (
                ffmpeg
                    .input("output_hoped.mp4")
                    .trim(start_frame=0, end_frame= clip_length)
                    .output(t_final)
                    .overwrite_output()
                    .run()
            )
            
            #shutil.copy(origin+file_name, t_final)        
    else: 
        print(file_name + " not in origin", origin, "not copied")

50 files copied
100 files copied
150 files copied
200 files copied
250 files copied
300 files copied
350 files copied
400 files copied
450 files copied
500 files copied
550 files copied
600 files copied
650 files copied
700 files copied
750 files copied
800 files copied
850 files copied
900 files copied
950 files copied
1000 files copied
1050 files copied
1100 files copied
1150 files copied
1200 files copied
1250 files copied
1300 files copied
1350 files copied
1400 files copied
1450 files copied
1500 files copied
1550 files copied
1600 files copied
1650 files copied